---
title: "Data Import"
output: github_document
---

This file is for practicing data imports.

```{r message=FALSE, echo=FALSE}
library(tidyverse)
library(readxl)
library(haven)
```

import dataset

```{r}
litters_df = 
  read_csv(file = 'data/FAS_litters.csv', 
           na = c("", "NA", "."))

litters_df = janitor::clean_names(litters_df)
litters_df
```

Import second dataset

```{r}
pups_df = 
  read_csv(file = "data/FAS_pups.csv", 
           na = c("", "NA", "."),
           skip= 3,
           skip_empty_rows = TRUE)

pups_df = janitor::clean_names(pups_df)
pups_df
```

Head / tail
```{r}
head(litters_df, 20)
tail(pups_df, 5)
```

```{r}
skimr::skim(pups_df)
```
```{r}
mlb_df = 
  read_excel('data/mlb11.xlsx')
```

Look at Data
```{r}
mlb_df
```
Import LotR words
```{r}
fotr_df = 
  read_excel("data/LotR_Words.xlsx",
             range = "B3:D6")

fotr_df

tt_df = 
  read_excel("data/LotR_Words.xlsx",
             range = "F3:H6")

tt_df
```

Read in the PULSE dataset

```{r}
  pulse_df = 
    read_sas("data/public_pulse_data.sas7bdat")

pulse_df = janitor::clean_names(pulse_df)
pulse_df
```




