---
title: "02_data_manipulation"
author: "Ian O'Keeffe"
date: "2026-09-24"
output: html_document
---

```{r}
library(tidyverse)
```

```{r}
litters_df <- read_csv('data/FAS_litters.csv',
                      na=c('', 'NA', '.'))

litters_df = janitor::clean_names((litters_df))

pups_df = read_csv(
  "data/FAS_pups.csv",
  skip = 3,
  na = c("", "NA", "."))

pups_df = janitor::clean_names(pups_df)
```

```{r}
select(litters_df, group, litter_number)

select(litters_df, group:gd_of_birth)

select(litters_df, -group)

select(litters_df, starts_with("gd"))

select(litters_df, starts_with("gd"), group)

select(litters_df, GROUP = group, everything())

select(litters_df, -starts_with('gd'))
```

```{r}
rename(litters_df, GROUP = group)

relocate(litters_df, litter_number, gd0_weight)

select(pups_df, litter_number, sex, pd_ears)
```

```{r}
filter(litters_df, gd_of_birth == 19)
filter(litters_df, pups_born_alive < 5)
filter(litters_df, pups_born_alive != 6)

filter(litters_df, group %in% c("Con7", "Con8"))
filter(litters_df, group %in% c("Con7", "Con8"), pups_born_alive == 7)



```

```{r}
pups_df
```

```{r}
filter(pups_df, pd_walk < 11, sex == 2)
```

```{r}
mutate(litters_df, 
       wt_gain = gd18_weight - gd0_weight,
       wt_gain_squared = wt_gain^2,
       group = str_to_lower(group))
```

```{r}
arrange(litters_df, pups_born_alive)
arrange(litters_df, desc(pups_born_alive))
```
```{r}
litters_df = 
  read_csv("data/FAS_litters.csv", na = c("", "NA", ".")) %>% 
  janitor::clean_names() %>% 
  select(group, starts_with("gd")) %>% 
  drop_na() %>% 
  mutate(
    wt_gain = gd18_weight - gd0_weight,
    group = str_to_lower(group)
  )

litters_df
```
```{r}
pups_df
```

```{r}
pups_df = read_csv("data/FAS_pups.csv", skip = 3, na = c("", "NA", ".")) %>% 
  janitor::clean_names() %>% 
  drop_na() %>% 
  select(starts_with("pd"), litter_number) %>% 
  mutate(pd_walk_minus_7 = pd_walk - 7)

pups_df
```
```{r}
litters_df %>%
  filter(group %in% c("con7", 'con8')) %>% 
  lm(gd18_weight ~ gd0_weight, data = .)
```


