---
title: "Tidy Data"
author: "Ian O'Keeffe"
date: "2026-09-29"
output: html_document
---
This file is for doing data tidying
```{r}
library(tidyverse)

data('mtcars')
```

## Let's tidy some data
```{r}
pulse_df = 
  haven::read_sas('data/public_pulse_data.sas7bdat') %>% 
  janitor::clean_names()
```
Data is embedded in column names, let's fix that. baseline, one month, 6 months are column names. we'll pivot out and add new names.

names_prefix clears leading characters. names_to gives a new column with old column heads
```{r}
pulse_tidy_df = 
  pulse_df %>% 
  pivot_longer(
    bdi_score_bl:bdi_score_12m,
    names_to = "visit",
    names_prefix = "bdi_score_",
    values_to = "bdi_score"
  ) %>% 
  mutate(
    visit = replace(visit, visit == "bl", "00m")
  )
pulse_tidy_df
```
```{r}
litters = 
  read_csv("data/FAS_litters.csv", na = c("", "NA", ".")) %>% 
  janitor::clean_names()

litters
```

```{r}


litters = 
  read_csv("data/FAS_litters.csv", na = c("", "NA", ".")) %>% 
  janitor::clean_names() %>% 
  select(litter_number, gd0_weight, gd18_weight) %>% 
  pivot_longer(
    gd0_weight:gd18_weight,
    names_to = "gd",
    values_to = "weight"
  ) %>% 
  mutate(
    gd = case_match(
      gd,
      "gd0_weight" ~ 0,
      "gd18_weight" ~ 18,
    )
  )

litters
```

```{r}

```


